version: '2'
services:
  newapps1-app:
    image: newapps1
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://newapps1-postgresql:5432/newapps1
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8008:8008
  newapps1-postgresql:
    extends:
      file: postgresql.yml
      service: newapps1-postgresql
