CREATE TABLE "e1" ("t11" INT NOT NULL, "t12" CHAR (20) NOT NULL, CONSTRAINT "pk_constraint_e1" PRIMARY KEY ("t11"));
CREATE TABLE "e2" ("e21" INT NOT NULL, "e22" CHAR (10) NOT NULL, CONSTRAINT "pk_constraint_e2" PRIMARY KEY ("e21"));
